
export const COMMON_CARD_STEP_THRESHOLD = 100;
export const SEMI_RARE_CARD_SPEED_THRESHOLD_KMH = 15;
export const SEMI_RARE_CARD_COOLDOWN_MS = 10000;
export const RARE_CARD_DISTANCE_THRESHOLD_M = 6000;
export const MAX_REALISTIC_SPEED_KMH = 50;
export const STEP_DETECTION_THRESHOLD = 12; // m/s^2
export const MIN_STEP_INTERVAL_MS = 250;
export const MAX_STEP_INTERVAL_MS = 700;
